#ifndef DEFINITIONS_H
#define DEFINITIONS_H




#ifdef STATICDLL_EXPORTS
   #define STATICDLL_API __declspec(dllexport)
#else
   #define STATICDLL_API __declspec(dllimport)
#endif


namespace StaticDLL{
	class EnumDLL{
		public:
			enum KEYS{UP,DOWN,LEFT,RIGHT};
			enum STATES{DEFAULT = -2,NONE = -1, QUIT, RETURN, MAINMENU,OPTIONS,MAPOPTIONS, LOAD, ABOUT, SAVE, NEW, EDITORMODE, EDITORMAINMENU, EDITORMAPOPTIONS, EDITORSCREENOPTIONS, EDITOROPTIONS, TILEIMAGEPICKER, TILETYPEPICKER, TILECOLORPICKER, OBJECTIMAGEPICKER, ENEMYPICKER};
			enum STATEDIRECTION{NA,PUSH,POP,POPPUSH,POPTOFIRST};
			enum TILETYPE{EMPTYTILE, SOLIDTILE, COLLISIONTOPTILE, COLLISIONLEFTTILE, COLLISIONRIGHTTILE, ILLUSIONTILE};
			enum OPTIONTYPES{NOOPTION,WIDTHOPTION,HEIGHTOPTION};
			enum OVERLAYACTIONS{OVERLAYNONE,OVERLAYOPENING,OVERLAYCLOSING, OVERLAYHEADERCLICKED};
			enum OVERLAYSTATE{OVERLAYOPENED,OVERLAYCLOSED};

			//enum CHARACTERSTATES{CHARACTERIDLE, CHARACTERMOVING, CHARACTERJUMPING, CHARACTERFALLING, CHARACTERONGROUND};
			enum CHARACTERYAXISSTATES{CHARACTERJUMPING, CHARACTERFALLING, CHARACTERONGROUND};
			enum CHARACTERFACINGDIRECTION{CHARACTERLEFT, CHARACTERRIGHT};


			enum IMAGESETS{PLAYERIMAGESET, TILEIMAGESET, TILECOLORSET, BACKGROUNDIMAGESET, SYSTEMIMAGESET, OBJECTIMAGESET, ENEMYIMAGESET};
	};

	class Constants{
		public:
			static const double TileSize() { return 20.0; }


	};

}




#endif